### PR TITLE
Use hash router instead of normal URLs

### LINKED ISSUE #47: 404 after page reload on create wallet
Steps: 
1. Click Create new Wallet
2. on the mnemonics page try to reload (reload / Command+R)
3. you get the 404

Try the same with one and 2 steps further, on the mnemonics confirmation page and passwords setup, same issue. 

The same for the recover wallet from mnemonics and import wallet file.

Screenshot 2024-07-24 at 21 44 16

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #47

### CODE REVIEW

**Comment by dioexul** [comment]
Validated. No more 404 (checked different pages)

**Review by monikasmolarek — COMMENTED** [review]
No 404, but:
- when we're logged in, we are logged out after each page refresh
- on wallet create, confirm mnemonics step, the refresh sends back to the main page, so if someone noted the 24 words and the page refreshed, it's lost.
- on recover from mnemonics, once all the 24 words typed in, on the next step- set up password, once refreshed, we're back on the main page and have to type the words again (might be frustrating if the mnemonics are on the piece of paper, no copy-paste

Not sure about the above aspects, definitely not a priority right now, but it would be cool to clean up this behaviour someday.

**Comment by brusherru** [comment]
@monikasmolarek yeah, page refresh cleans up everything.
And this behaviour was the same previously (if you run it on localhost, where it serves SPA correctly).
So it's not a regression :)

Also, if we want to have a persistent state between "refreshes" then we will have the non-secret data (which we may want to keep private) decrypted in the local storage. So basically it will be the same as not asking password to unlock the wallet.

Anyway, if we want to have something like this, we need to define how and then implement it separately.

**Comment by pigmej** [comment]
Imo the current behavior is correct. As Kirill stated, making persistence
between steps would mean that we keep the state somewhere, and that state
would need to contain super critical data.

**Pull request merged**
