### PR TITLE
Use AES-CTR + ARGON2 + HMAC instead of AES-GCM

### PR DESCRIPTION
**Pull request by brusherru**
It keep support of importing Smapp's wallet format and AES-GCM encrypted wallet file, but it will re-encrypt it using Argon2.

Since Argon2 with the selected params requires more computation and takes more time to decrypt/encrypt I've added "waiting" states to the buttons, which works with secret data, such as button in password modal, buttons on unlock and import screens.

P.S.
This implementation uses the same Argon2 params for storing wallet inside local storage (App's persistent memory) and for the exported wallet file. But mb we'd better have two different params for them to have fast speed in App and safest wallet file on FS?

### CODE REVIEW

**Comment by brusherru** [comment]
I've also tested it on iPhone 15 Pro, works well and has approximately the same encrypt/decrypt time :)

**Review by dioexul — APPROVED** [review]
Checked on Chrome - works for me (load file from prod, save, clean up, load again).
If I save this file and try to load on prod it says "wrong password" - error message is there, but not correct.
I didn't try to brute force the file. Probably we can ask Halborn to validate.

**Comment by brusherru** [comment]
> If I save this file and try to load on prod it says "wrong password" - error message is there, but not correct.

Yeah, that's correct because this changes introduces new encryption method (Key Derivation Function, to be more precise). So the old one does not support it. If we will need to export using old encryption method — it is still possible and easy to do. However, Smapp-lite uses a newer wallet format, which is not support in Smapp and Smcli. So I don't think we need it :)

**Review by monikasmolarek — APPROVED** [review]

**Review by pigmej — APPROVED** [review]
It may be slower than expected but at least its' secure.

**Pull request merged**
