### PR TITLE
Fix: lock wallet on minimizing / unfocusing entire browser window

### LINKED ISSUE #64: Recheck: Lock on unfocused app after 2 min
When we leave the wallet on an inactive/unfocused tab, it doesn’t matter how much time passes or whether or not the PC is idle. The countdown and auto-logout don't work.

**Case 1:** leave the wallet in the background (unfocused tab) and leave the PC idle, with no keys/mouse events whatsoever:

https://github.com/user-attachments/assets/c4490991-810e-41f6-8086-543de162605a

If the wallet is in the opened/active tab and the browser is opened but left idle, it works as expected.

**Case 2:** leave the wallet in the background, both as opened/active tab or second/unfocused tab, work elsewhere, get back to the browser: 

https://github.com/user-attachments/assets/9127b0f0-2b1b-40c2-99eb-80209dcbee9a

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #64

### CODE REVIEW

**Review by monikasmolarek — CHANGES_REQUESTED** [review]
I don't see any change in the timeout behavior. It's the same - a minimized browser or being on a different tab keeps the wallet logged in forever with only a flickering countdown modal.

**Comment by brusherru** [comment]
@monikasmolarek hmm, but it works for me. 🤔 

I've doubled checked all of these cases:
1. switching tab
2. minimizing browser
3. switching to another screen and another app
Both in Chrome and Safari...

Did you waited enough?
It requires 2 minute to start the 30 seconds countdown.
So you need to wait for 2.5+ minutes to lock the wallet.

The only case when it does not lock for me if I lock the macbook.
For this case I can check if it were focused after some time — then lock immediately 🤔

**Comment by monikasmolarek** [comment]
Just not to leave this thread "ignored", I replied to Kirill on Slack while GH was down, showed recordings and it seems this issue should be investigated further/fixed differently.

**Comment by dioexul** [comment]
Checked. The 30s counted turned on right after 2 minutes in both cases - when the window is "active" and when the window is "not active" (I do smth in another app, the window is observed in the background). 
Note: incognito tab was used. MacOS, Chrome.

**Comment by brusherru** [comment]
Added a tiny fix that fixes #51 :)

**Review by monikasmolarek — COMMENTED** [review]
So the infinite loop seems to be gone, that's great!
But I still have the same issue with the wallet not timing out properly. Please someone else check it properly. Maybe it's specifically only my persoanl setup...

**Review by monikasmolarek — COMMENTED** [review]
I'm back home after time off and I tested it on my second laptop with windows. 
It's still the same - the flickering modal and the wallet stays logged-in. 

I also removed all the Chrome extensions and turned off all the programs working in the background. Still the same. 

I tested it with sleep mode on and off (with a longer than 5 minutes idle time settings)

I also checked anther web browser on Windows. It's still logged in.

**Comment by pigmej** [comment]
It works for me, tested with firefox and opera on macos.

**Review by pigmej — APPROVED** [review]

**Pull request merged**
